<Project>

  <PropertyGroup>
    <!-- Enable prelude by default -->
    <_UseTyneCorePrelude>true</_UseTyneCorePrelude>
    <!-- Disable if disabled across Tyne -->
    <_UseTyneCorePrelude Condition=" '$(TynePrelude)' == 'disable' ">false</_UseTyneCorePrelude>
    <!-- Disable if disabled specifically -->
    <_UseTyneCorePrelude Condition=" $(TyneCorePrelude) == 'disable' ">false</_UseTyneCorePrelude>
  </PropertyGroup>

  <ItemGroup Condition="$(_UseTyneCorePrelude)">
    <Using Static="true" Include="Tyne.Preludes.Core.ResultPrelude"/>
    <Using Static="true" Include="Tyne.Preludes.Core.UnitPrelude"/>
  </ItemGroup>

</Project>
