<Project>

  <PropertyGroup>
    <TargetFrameworks>$(TyneSupportedFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <!-- Add common testing packages. -->
  <ItemGroup>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NSubstitute.Analyzers.CSharp" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup Condition=" '$(IsTestProject)' != 'true' ">
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Assertions" />
  </ItemGroup>

  <ItemGroup Condition=" '$(IsTestProject)' == 'true' ">
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <!-- Configures global usings for very common namespaces in test projects. -->
  <ItemGroup Label="Global usings">
    <Using Include="NSubstitute" />
    <using Include="TUnit.Assertions.AssertConditions.Throws" />
  </ItemGroup>

  <!-- These warnings can be ignored for test code. -->
  <PropertyGroup Label="Warnings and errors">
    <!--
      CA1707: Identifiers should not contain underscores.
      REASON: Underscores help clarify what test cases are testing.
    -->
    <NoWarn>$(NoWarn);CA1707</NoWarn>
    <!--
      CA1819: Properties should not return arrays.
      REASON: This is useful for providing theories with member data in tests.
    -->
    <NoWarn>$(NoWarn);CA1819</NoWarn>
    <!--
      CS1591: Missing XML comment for publicly visible type or member.
      REASON: Tests aren't shipped so we don't care about missing XML comments.
              See Build.props for why this is surfaced.
    -->
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <!--
      CA1822: Mark members as static.
      REASON: Test methods are conventionally instanced.
    -->
    <NoWarn>$(NoWarn);CA1822</NoWarn>
    <!--
      CA1515: Because an application's API isn't typically referenced from outside the assembly, types can be made internal.
      REASON: Unit tests should be publically visible.
    -->
    <NoWarn>$(NoWarn);CA1515</NoWarn>
    <!--
      IDE0058: Remove unnecessary expression value
      REASON:  Assertions return builders for chaining, and writing `_ = ` before every assertion is tedious.
    -->
    <NoWarn>$(NoWarn);IDE0058</NoWarn>
  </PropertyGroup>

</Project>
