<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>Tyne.Core.Tests</AssemblyName>
        <RootNamespace>Tyne</RootNamespace>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="$(SrcRoot)\Tyne.Core\Core.csproj"/>
        <ProjectReference Include="$(SrcRoot)\Tyne.Core.TestUtilities\Core.TestUtilities.csproj"/>
    </ItemGroup>

    <Import Project="$(EngRoot)\Testing.props"/>

</Project>
