namespace Tyne.Aerospace.Client.Features.Systems.Filtering.Values.Search;

public static class Galaxies
{
    public static readonly IReadOnlyList<GalaxyInfo> Instance =
    [
        new("Andromeda", "SA(s)b", "Andromeda"),
        new("Milky Way", "SBbc", "Sagittarius (centre)"),
        new("Triangulum", "SA(s)cd", "Triangulum"),
        new("Large Magellanic Cloud", "Irr/SB(s)m", "Dorado"),
        new("NGC 3109", "SB(s)m", "Hydra"),
        new("Messier 32", "E2", "Andromeda"),
        new("Wolf-Lundmark-Melotte", "Ir+", "Cetus"),
        new("IC 10", "KBm or Ir+", "Cassiopeia"),
        new("Small Magellanic Cloud", "SB(s)m pec", "Tucana"),
        new("Pisces Dwarf", "Irr", "Pisces"),
        new("IC 1613", "IAB(s)m V", "Cetus"),
        new("Phoenix Dwarf", "Irr", "Phoenix"),
        new("Leo A", "IBm V", "Leo"),
        new("Aquarius Dwarf", "IB(s)m", "Aquarius"),
        new("SagDIG", "IB(s)m V", "Sagittarius"),
        new("NGC 6822", "IB(s)m IV-V", "Sagittarius"),
        new("Pegasus Dwarf", "Irr", "Pegasus"),
        new("UGC 4879", "IAm", "Ursa Major"),
        new("Sextans A", "Ir+V", "Sextans"),
        new("Sextans B", "Ir+IV-V", "Sextans"),
        new("Leo P", "Irr", "Leo"),
        new("AGC 198606", "Irr?", "Leo"),
        new("AGC 215417", "Irr?", "Leo"),
        new("AGC 219656", "Irr?", "Leo"),
        new("AGC 249525", "Irr?", "Boötes"),
        new("AGC 268069", "Irr?", "Serpens"),
        new("Messier 110", "dE6p", "Andromeda"),
        new("NGC 147", "dE5 pec", "Cassiopeia"),
        new("Boötes I", "dSph", "Boötes"),
        new("Cetus Dwarf", "dSph/E4", "Cetus"),
        new("Canes Venatici I Dwarf", "dSph", "Canes Venatici"),
        new("Canes Venatici II Dwarf", "dSph", "Canes Venatici"),
        new("Andromeda III", "dE2", "Andromeda"),
        new("NGC 185", "dE3 pec", "Cassiopeia"),
        new("Andromeda I", "dE3 pec", "Andromeda"),
        new("Sculptor Dwarf (E351-G30)", "dE3", "Sculptor"),
        new("Andromeda V", "dSph", "Andromeda"),
        new("Andromeda II", "dE0", "Andromeda"),
        new("Fornax Dwarf", "dSph/E2", "Fornax"),
        new("Carina Dwarf", "dE3", "Carina"),
        new("Leo I", "dE3", "Leo"),
        new("Sextans Dwarf", "dE3", "Sextans"),
        new("Leo II", "dE0 pec", "Leo"),
        new("Ursa Minor Dwarf", "dE4", "Ursa Minor"),
        new("Draco Dwarf", "dE0 pec", "Draco"),
        new("SagDSG", "dSph/E7", "Sagittarius"),
        new("Tucana Dwarf", "dE5", "Tucana"),
        new("Cassiopeia Dwarf", "dSph", "Cassiopeia"),
        new("Pegasus Dwarf Spheroidal", "dSph", "Pegasus"),
        new("Ursa Major I Dwarf", "dSph", "Ursa Major"),
        new("Ursa Major II Dwarf", "dSph", "Ursa Major"),
        new("Leo IV", "dSph", "Leo"),
        new("Leo V", "dSph", "Leo"),
        new("Leo T", "dSph/Irr", "Leo"),
        new("Boötes II", "dSph", "Boötes"),
        new("Boötes III", "dSph", "Boötes"),
        new("Boötes IV", "dSph", "Boötes"),
        new("Coma Berenices", "dSph", "Coma Berenices"),
        new("Segue 2", "dSph", "Aries"),
        new("Hercules", "dSph", "Hercules"),
        new("Pisces II", "dSph", "Pisces"),
        new("Reticulum II", "dSph", "Reticulum"),
        new("Reticulum III", "dSph", "Reticulum"),
        new("Eridanus II", "dSph", "Eridanus"),
        new("Grus I", "dSph", "Grus"),
        new("Grus II", "dSph", "Grus"),
        new("Tucana II", "dSph", "Tucana"),
        new("Hydrus I", "dSph", "Hydrus"),
        new("Draco II", "dSph", "Draco"),
        new("Carina III", "dSph", "Carina"),
        new("Triangulum II", "dSph", "Triangulum"),
        new("Carina II", "dSph", "Carina"),
        new("Pictor II", "dSph", "Pictor"),
        new("Horologium II", "dSph", "Horologium"),
        new("Virgo I", "dSph", "Virgo"),
        new("Aquarius II", "dSph", "Aquarius"),
        new("Crater II", "dSph", "Crater"),
        new("Hydra II", "dSph", "Hydra"),
        new("Antlia II", "dSph", "Antlia"),
        new("Pegasus III", "dSph", "Pegasus"),
        new("Pegasus IV", "dSph", "Pegasus"),
        new("Pegasus W", "dSph", "Pegasus"),
        new("Cetus III", "dSph", "Cetus"),
        new("Tucana B", "dSph", "Tucana"),
        new("Perseus I Dwarf", "dE", "Perseus"),
        new("Antlia Dwarf", "dE3/dSph/Irr?", "Antlia"),
        new("Andromeda IX", "dSph", "Andromeda"),
        new("Andromeda X", "dSph", "Andromeda"),
        new("Andromeda XI", "dSph", "Andromeda"),
        new("Andromeda XII", "dSph", "Andromeda"),
        new("Andromeda XIII", "dSph", "Andromeda"),
        new("Andromeda XIV", "dSph", "Pisces"),
        new("Andromeda XV", "dSph", "Andromeda"),
        new("Andromeda XVII", "dSph", "Andromeda"),
        new("Andromeda XIX", "dSph", "Andromeda"),
        new("Andromeda XX", "dSph", "Andromeda"),
        new("Andromeda XXI", "dSph", "Andromeda"),
        new("Andromeda XXII", "dSph", "Pisces"),
        new("Andromeda XXIII", "dSph", "Andromeda"),
        new("Andromeda XXIV", "dSph", "Andromeda"),
        new("Andromeda XXV", "dSph", "Andromeda"),
        new("Andromeda XXVI", "dSph", "Andromeda"),
        new("Andromeda XXVII", "dSph", "Andromeda"),
        new("Andromeda XXIX", "dSph", "Pegasus"),
        new("Andromeda XXX", "dSph?", "Cassiopeia"),
        new("Andromeda XXXI", "dSph?", "Lacerta"),
        new("Andromeda XXXII", "dSph?", "Cassiopeia"),
        new("Andromeda XXXIV", "dSph", "Pegasus"),
        new("Andromeda XVI", "dSph", "Pisces"),
        new("Andromeda XXVIII", "dSph?", "Pegasus"),
        new("Andromeda XXXIII", "dSph?", "Perseus"),
        new("Andromeda XVIII", "dSph", "Andromeda"),
        new("Centaurus I", "dSph", "Centaurus"),
        new("Pisces VII", "dSph?", "Pisces")
    ];
}
