name: PR build and test

on:
  pull_request:

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup .NET ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
            9.x

      - name: .NET SDKs
        run: dotnet --list-sdks
          
      - name: Setup workloads
        run: dotnet workload install wasm-tools
          
      - name: Restore packages
        run: dotnet restore
          
      - name: Restore tools
        run: dotnet tool restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore /p:GITHUB_ACTIONS=true
        
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
      
      - name: Verify packable
        run: dotnet pack --configuration Release --no-build --output ./artifacts/nupkgs

      - name: Build docs
        run: dotnet docfx docs/docfx.json
