name: PR build and test

on:
  pull_request:

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '8.0.x' ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup .NET ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
          
      - name: Setup workloads
        run: dotnet workload install wasm-tools
          
      - name: Restore packages
        run: dotnet restore
          
      - name: Restore tools
        run: dotnet tool restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore /p:GITHUB_ACTIONS=true
        
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
      
      - name: Verify packable
        run: dotnet pack --configuration Release --no-build --output ./artifacts/nupkgs

      - name: Build docs
        run: dotnet docfx docs/docfx.json
