name: PR check formatting

on: pull_request

jobs:
  dotnet-format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Add problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1

      - name: Setup .NET ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
            9.x

      - name: .NET SDKs
        run: dotnet --list-sdks

      - name: dotnet tool restore
        run: dotnet tool restore

      - name: dotnet format
        uses: xt0rted/dotnet-format@v1
        with:
          only-changed-files: "true"
