name: Test and Publish

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Publish Project
      run: dotnet publish src/Tyne.Docs/src/Tyne.Docs.csproj -c Release -o release --nologo

    - name: Update base url
      run: sed -i 's/<base href="\/" \/>/<base href="\/Tyne\/" \/>/g' release/wwwroot/index.html

    - name: Add .nojekyll
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot