name: Publish release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Setup version
        run: echo "PACKAGE_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: 'refs/tags/v${{ env.PACKAGE_VERSION }}'

      - name: Setup solution
        uses: ./.github/actions/setup

      - name: Build solution
        uses: ./.github/actions/build-solution

      - name: Test solution
        uses: ./.github/actions/test

      - name: Build packages
        uses: ./.github/actions/build-packages

      - name: Build docs
        uses: ./.github/actions/build-docs
        with:
          package-version: '${{ env.PACKAGE_VERSION }}'

     - name: Publish packages
       uses: ./.github/actions/publish-packages

     - name: Publish docs
       uses: ./.github/actions/publish-docs
